default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

DeepMindHumanoidBrain:
    num_epoch: 10 
    time_horizon: 1000
    summary_freq: 250000
    use_recurrent: false
    normalize: false 
    num_layers: 2
    hidden_units: 64
    learning_rate: 3e-4
    batch_size: 64
    buffer_size: 10240
    beta: .003
    max_steps: 10.e6

MarathonManBrain:
    num_epoch: 10 
    time_horizon: 100 
    summary_freq: 250000
    use_recurrent: false
    normalize: false 
    num_layers: 2
    hidden_units: 64
    learning_rate: 3e-4
    batch_size: 64
    buffer_size: 10240
    beta: .003
    max_steps: 10.e6    

SparseMarathonManBrain:
    num_epoch: 10 
    time_horizon: 3000 
    summary_freq: 250000
    use_recurrent: false
    normalize: false 
    num_layers: 2
    hidden_units: 64
    learning_rate: 3e-4
    batch_size: 64
    buffer_size: 10240
    beta: .003
    max_steps: 10.e6  

SparseMarathonManRewardHackBrain: 
    num_epoch: 10 
    time_horizon: 300000 
    summary_freq: 250000
    use_recurrent: false
    normalize: false 
    num_layers: 2
    hidden_units: 64
    learning_rate: 3e-4
    batch_size: 64
    buffer_size: 10240
    beta: .003
    max_steps: 20.e6

RewardHackBrain:
    summary_freq: 250000
    # num_epoch: 10 
    num_layers: 2
    hidden_units: 20
    learning_rate: 1e-3
    max_steps: 20.e6

DeepMindHopperBrain:
    num_epoch: 10 
    time_horizon: 100 
    summary_freq: 100000
    use_recurrent: false
    normalize: false 
    num_layers: 2
    hidden_units: 64
    learning_rate: 3e-4
    batch_size: 64
    buffer_size: 2048 
    beta: .003
    max_steps: 1.e6

DeepMindWalkerBrain:
    num_epoch: 10 
    time_horizon: 100 
    summary_freq: 100000
    use_recurrent: false
    normalize: false 
    num_layers: 2
    hidden_units: 64
    learning_rate: 3e-4
    batch_size: 64
    buffer_size: 2048 
    beta: .003
    max_steps: 1.e6

OpenAIAntBrain:
    num_epoch: 10 
    time_horizon: 100 
    summary_freq: 100000
    use_recurrent: false
    normalize: false 
    num_layers: 2
    hidden_units: 64
    learning_rate: 3e-4
    batch_size: 64
    buffer_size: 2048 
    beta: .003
    max_steps: 1.e6
